export const ALL = 'all' 
export const CABIN = 'cabin'
export const CABIN_ID = 'cabin_id'
export const CABIN_IMAGE_SELECT_DETAIL = 'image'
export const CABIN_SELECT_DETAIL = 'name price price_high jacuzzi capacity kitchen tv wifi detail'
export const HOURS_IN_DAY = 24
export const ID = '_id'
export const MAX_LENGTH_CODE = 12
export const MIN_LENGTH_CODE = 8
export const OFFSET_MINUTES = 60
export const SECONDS_IN_DAY = 86400
export const SECONDS_TO_MILISECONDS = 1000
export const SEVERITY_ERROR = 'error'
export const SEVERITY_INFO = 'info'
export const SEVERITY_SUCCESS = 'success'
export const SEVERITY_WARN = 'warn'
export const SPECIALPACK_ID = 'specialpack_id'
export const TOAST_TIMEOUT = 3000